# Generated by Django 5.0.6 on 2024-09-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ja", "0002_alter_ja_userconfirmation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ja",
            name="userconfirmation",
        ),
    ]
