# Generated by Django 5.0.6 on 2024-09-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("ja", "0003_remove_ja_userconfirmation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyer",
            name="walet",
        ),
        migrations.RemoveField(
            model_name="owner",
            name="walet",
        ),
        migrations.AddField(
            model_name="buyer",
            name="create",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="owner",
            name="create",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="owner",
            name="update",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="owner",
            name="wallet",
            field=models.BigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Suporter",
        ),
    ]
